-- Tạo USER sử dụng TABLESPACE mặc định
CREATE USER qlvexemphim IDENTIFIED BY phim123;

-- Gán quyền cho user mới
GRANT CONNECT, RESOURCE TO qlvexemphim;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE PROCEDURE TO qlvexemphim;